version: '3'

services:
   db:
     image: image2
     restart: always
     hostname: db
     environment:
       MYSQL_ROOT_PASSWORD: 2015
       MYSQL_DATABASE: mydb
       MYSQL_USER: root
       
   webapi:
     depends_on:
       - db
     image: image1
     hostname: webapi
     ports:
       - "8081:8080"
     restart: always
